;;;; ethernet.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import chicken scheme defstruct extras srfi-13 defstruct))
(##sys#register-compiled-module
  'ethernet
  (list)
  '((broadcast-mac . ethernet#broadcast-mac)
    (make-ethernet-frame . ethernet#make-ethernet-frame)
    (ethernet-frame-dst . ethernet#ethernet-frame-dst)
    (ethernet-frame-src . ethernet#ethernet-frame-src)
    (ethernet-frame-ethertype . ethernet#ethernet-frame-ethertype)
    (ethernet-frame-payload . ethernet#ethernet-frame-payload)
    (ethernet-frame-dot1q . ethernet#ethernet-frame-dot1q)
    (read-ethernet-frame . ethernet#read-ethernet-frame)
    (write-ethernet-frame . ethernet#write-ethernet-frame))
  (list)
  (list))

;; END OF FILE
